### ISSUE TITLE
Decision logs

### ISSUE THREAD

**Issue by marcoooo** [rohitxsh/ensembl_lakehouse#1]
Decision log trace to 
- abandon get away from DRF and move to Fast API
- to create a GET endpoint and not POST

**Comment by rohitxsh** [comment]
Why not Django?
1. Using ORM will create dependency to maintain these models, which can be done by using the tables from AWS Glue instead which holds the meta schema for the parquet files.
2. Because of the above reason we won't be able to use one of the core features of Django framework i.e. it's ORM
3. Also as it's only a backend app so templates won't be used here
4. So moving to a more simpler and lighter framework makes more sense here as most of the Django core features are not required, connection to Athena will be handled by PyAthena and SQLAlchemy

**Comment by rohitxsh** [comment]
Why GET endpoint?
1. Select type of requests should be GET
2. Easier to manage/implement and bookmarkable/shareable
3. For current use-case it won't exceed the URL character limit

**Comment by rohitxsh** [comment]
Why Boto3, not PyAthena
- Performance is much better with Boto3 as result data increases
- For reference:
https://medium.com/codex/connecting-to-aws-athena-databases-using-python-4a9194427638

**Comment by rohitxsh** [comment]
API hierarchy: Data (table) -> Species
Current BioMart has same flow, data is structured in AWS in same hierarchy
